spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: varg
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    secret: yourSuperSecretKeyThatShouldBeLongAndRandomForProduction
    access:
      token:
        expiration:
          ms: 900000     # 15 минут
    refresh:
      token:
        expiration:
          ms: 604800000  # 7 дней